In [2]:
import os
import pandas as pd
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

In [3]:
dialogue_paths = {case: f"results/extract_dialogue/aligned_fb_detection/LFB{case}_full 'dialogue'.csv" for case in [1, 2, 9, 10, 18]}
dialogue_dfs = {case: pd.read_csv(path) for case, path in dialogue_paths.items()}
dialogue_df = pd.concat(dialogue_dfs.values(), ignore_index=True)

dialogue_cm = confusion_matrix(dialogue_df['true_fb_instance'], dialogue_df['pred_fb_instance'])
dialogue_cm

array([[2144,  358],
       [ 474,  613]])

In [4]:
hall_paths = {case: f"results/extract_dialogue/aligned_fb_detection/LFB{case}_full 'reduced hallucinations'.csv" for case in [1, 2, 9, 10, 18]}
hall_dfs = {case: pd.read_csv(path) for case, path in hall_paths.items()}
hall_df = pd.concat(hall_dfs.values(), ignore_index=True)

hall_cm = confusion_matrix(hall_df['true_fb_instance'], hall_df['pred_fb_instance'])
hall_cm

array([[502, 197],
       [180, 500]])

In [5]:
id_paths = {case: f"results/extract_dialogue/aligned_fb_detection/LFB{case}_full 'all phrases'.csv" for case in [1, 2, 9, 10, 18]}
id_dfs = {case: pd.read_csv(path).replace(np.nan, None) for case, path in id_paths.items()}
id_df = pd.concat(id_dfs.values(), ignore_index=True)

id_cm = confusion_matrix(id_df['true_fb_instance'], id_df['pred_fb_instance'])
id_cm

array([[656, 115],
       [115, 493]])

In [6]:
fb_annot_df = pd.read_csv('../../clips_no_wiggle/fbk_cuts_no_wiggle_0_4210.csv')

In [13]:
ratios = []

for case_id in range(1, 34):
    if case_id not in id_dfs:
        continue
    
    annot_df = fb_annot_df[fb_annot_df['Case'] == case_id]

    aligned_human_annotations = set()
    for i in range(len(id_dfs[case_id])):
        annotations = id_dfs[case_id].iloc[i]['human_annotations']
        times = id_dfs[case_id].iloc[i]['human_annotations_times']
        if annotations == None:
            continue

        annotations_list = [x.split(':')[1][1:] for x in annotations.split('\n')[1:-1]]
        times_list = [":".join(x.split(':')[1:]).strip() for x in times.split('\n')[1:-1]]
        
        for i in range(len(annotations_list)):
            aligned_human_annotations.add((annotations_list[i], times_list[i]))

    aligned_human_annotations = sorted(list(aligned_human_annotations), key=lambda x: x[1])
    
    ratios.append(len(aligned_human_annotations) / len(annot_df))

In [14]:
ratios

[0.8107344632768362, 0.8186813186813187, 0.6, 0.8100558659217877, 0.79]

In [10]:
len(aligned_human_annotations), len(annot_df)

(149, 182)